name: Convert .drawio to .svg

on:
  push:
    paths:
      - 'img/*.drawio'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb libgtk-3-0 libxss1 libnss3 libx11-xcb1

      - name: Download draw.io AppImage
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v27.0.9/drawio-x86_64-27.0.9.AppImage
          chmod +x draw.io-27.0.9-x86_64.AppImage

      - name: Convert .drawio to .svg
        run: |
          for file in img/*.drawio; do
            base=$(basename "$file" .drawio)
            xvfb-run --auto-servernum ./draw.io-27.0.9-x86_64.AppImage --no-sandbox -x -f svg -o img/${base}.svg "$file"
          done

      - name: Commit and push SVG files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add img/*.svg
          git commit -m "Auto-convert .drawio to .svg" || echo "No changes to commit"
          git push
