name: Export Draw.io ➝ SVG

on:
  push:
    paths: ['img/*.drawio']

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb libgtk-3-0 libxss1 libnss3 libx11-xcb1

      - name: Download draw.io AppImage
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v26.2.15/draw.io-26.2.15-x86_64.AppImage
          chmod +x draw.io-26.2.15-x86_64.AppImage

      - name: Convert .drawio to .svg
        run: |
          for file in img/*.drawio; do
            base=$(basename "$file" .drawio)
            xvfb-run --auto-servernum ./draw.io-26.2.15-x86_64.AppImage --no-sandbox -x -f svg -o img/${base}.svg "$file"
          done
    
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add img/*.svg
          git commit -m "Auto-export .drawio to .svg" || echo "No changes"
          git push
          
