name: Export Draw.io to SVG

on:
  push:
    paths:
      - 'img/*.drawio'

jobs:
  export-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb libgtk-3-0 libxss1 libnss3 libx11-xcb1

      - name: Download draw.io desktop (CLI)
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v27.0.9/drawio-amd64-27.0.9.deb
          sudo dpkg -i draw.io-amd64-21.6.3.deb || true
          sudo apt-get install -f -y

      - name: Convert .drawio to .svg
        run: |
          for file in img/*.drawio; do
            xvfb-run --auto-servernum /opt/drawio/drawio -x -f svg -o img "$file"
          done

      - name: Commit and push SVG files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add img/*.svg
          git commit -m "Auto-export SVG from Draw.io" || echo "No changes to commit"
          git push
